### ISSUE TITLE
Which FastText version does this use?

### ISSUE THREAD

**Issue by Blakeinstein** [yikun-li/visdom-satd-management-system#1]
I am trying to replicate the implementation of the paper for my research, and unfortunately, after a bit of effort fighting dated dependencies, I am stuck on the following error
```
ValueError: /app/fasttext_issue_300.bin has wrong file format!
```

I tried both 0.9.1 and 0.9.2 as 0.8.x requires cython not listed as a dependency in your docker images.

**Comment by Blakeinstein** [comment]
Okay 0.8.3 doesn't work either
```
2024-02-11 17:22:35 /app/processing/commentscanner.py:34: SyntaxWarning: "is not" with a literal. Did you mean "!="?
2024-02-11 17:22:35   if len(record) is not 1:
2024-02-11 17:22:35 /app/processing/issuescanner.py:34: SyntaxWarning: "is not" with a literal. Did you mean "!="?
2024-02-11 17:22:35   if len(record) is not 1:
2024-02-11 17:22:35 Traceback (most recent call last):
2024-02-11 17:22:35   File "server.py", line 2, in <module>
2024-02-11 17:22:35     from app import create_app
2024-02-11 17:22:35   File "/app/__init__.py", line 14, in <module>
2024-02-11 17:22:35     from app import routes
2024-02-11 17:22:35   File "/app/routes.py", line 3, in <module>
2024-02-11 17:22:35     from app.processing import comment_scanner, comment_classifier, issue_scanner
2024-02-11 17:22:35   File "/app/processing/__init__.py", line 20, in <module>
2024-02-11 17:22:35     word_processor = WordProcessor(os.environ.get("WORD_EMBEDDING_FILE"))
2024-02-11 17:22:35   File "/app/processing/wordprocesser.py", line 12, in __init__
2024-02-11 17:22:35     self._word_embedding = fasttext.load_model(word_embedding_file)
2024-02-11 17:22:35   File "fasttext/fasttext.pyx", line 146, in fasttext.fasttext.load_model
2024-02-11 17:22:35 ValueError: fastText: trained model cannot be opened!
```

**Comment by Blakeinstein** [comment]
okay this might be dump but I checked for the data, and its not here. The instructions do not mention where I can find the associated data. Can someone point me in the right direction?
